apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-dd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: secrets-store-csi-driver
    repoURL: https://github.com/himanshusharma-git/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
