apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csidriver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
      #server: in-cluster
    server: https://kubernetes.default.svc
    namespace: argocd 
  project: default
  source:
    path: datadog-privatelocation 
    repoURL: https://github.com/SnapLogic/dev-argocd-jobs.git
    targetRevision: CO-1021
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
