apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-csi-driver-datadog
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    path: apps-dev
    repoURL: https://github.com/himanshusharma-git/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
