apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/SnapLogic/SnapInfra.git
    targetRevision: HEAD
    path: namespace/
  destination:
    name: in-cluster
    namespace: default
