apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-private-location-worker
spec:
  selector:
    matchLabels:
      app: private-location
  template:
    metadata:
      labels:
        app: private-location
      name: datadog-private-location-worker
    spec:
      serviceAccountName: datadog-sa
      containers:
      - image: datadog/synthetics-private-location-worker
        imagePullPolicy: Always
        name: datadog-private-location-worker
        volumeMounts:
        - mountPath: /etc/datadog/synthetics-check-runner.json
          name: secrets-store-inline
          subPath: _admin_datadog_properties_file.json
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "datadog-ssm" 
