apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-ssm
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "/admin/datadog_properties_file.json"
          objectType: "ssmparameter"
