apiVersion: v1
kind: Pod
metadata:
  name: ssm-pod
spec:
  serviceAccountName: datadog
  containers:
  - args:
    - /bin/sh
    - -ec
    - cp /mnt/secrets-store/* /root ; while :; do echo '.'; sleep 5 ; done
    image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "datadog-ssm"

