apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-csi-driver-datadog
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    path: datadog-privatelocation/prod-datadog-deployment
    repoURL: https://github.com/SnapLogic/SnapInfra.git
    targetRevision: CO-1021
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
